use WG_QUICK_USERSPACE_IMPLEMENTATION instead of kernel impl if set

diff --git a/wg-quick b/wg-quick
--- a/wg-quick
+++ b/wg-quick
@@ -86,15 +86,27 @@ auto_su() {
 }
 
 add_if() {
+	# If the userspace impl variable is set, use it
+	if [[ $WG_QUICK_USERSPACE_IMPLEMENTATION ]]; then
+		if ! command -v "${WG_QUICK_USERSPACE_IMPLEMENTATION}" >/dev/null; then
+			echo "[!] WireGuard userspace implementation selected, but invalid command: ${WG_QUICK_USERSPACE_IMPLEMENTATION}" >&2
+			exit 1
+		fi
+		cmd "${WG_QUICK_USERSPACE_IMPLEMENTATION}" "$INTERFACE"
+		return
+	fi
+
+	# Try to use kernel implementation
 	local ret
 	if ! cmd ip link add "$INTERFACE" type wireguard; then
 		ret=$?
 		if [[ -e /sys/module/wireguard ]]; then
 			echo "[!] WireGuard kernel module detected, but failed to create interface" >&2
 			exit $ret
-		elif command -v "${WG_QUICK_USERSPACE_IMPLEMENTATION:-wireguard-go}" >/dev/null; then
-			echo "[!] Missing WireGuard kernel module. Falling back to slow userspace implementation." >&2
-			cmd "${WG_QUICK_USERSPACE_IMPLEMENTATION:-wireguard-go}" "$INTERFACE"
+		# Potentially fall back to wireguard-go
+		elif command -v wireguard-go >/dev/null; then
+			echo "[!] Missing WireGuard kernel module. Falling back to slow wireguard-go userspace implementation." >&2
+			cmd wireguard-go "$INTERFACE"
 		else
 			echo "[!] Missing WireGuard kernel module or userspace implementation." >&2
 			exit $ret
