make more clear error messages

diff --git a/wg-quick b/wg-quick
--- a/wg-quick
+++ b/wg-quick
@@ -89,9 +89,16 @@ add_if() {
 	local ret
 	if ! cmd ip link add "$INTERFACE" type wireguard; then
 		ret=$?
-		[[ -e /sys/module/wireguard ]] || ! command -v "${WG_QUICK_USERSPACE_IMPLEMENTATION:-wireguard-go}" >/dev/null && exit $ret
-		echo "[!] Missing WireGuard kernel module. Falling back to slow userspace implementation." >&2
-		cmd "${WG_QUICK_USERSPACE_IMPLEMENTATION:-wireguard-go}" "$INTERFACE"
+		if [[ -e /sys/module/wireguard ]]; then
+			echo "[!] WireGuard kernel module detected, but failed to create interface" >&2
+			exit $ret
+		elif command -v "${WG_QUICK_USERSPACE_IMPLEMENTATION:-wireguard-go}" >/dev/null; then
+			echo "[!] Missing WireGuard kernel module. Falling back to slow userspace implementation." >&2
+			cmd "${WG_QUICK_USERSPACE_IMPLEMENTATION:-wireguard-go}" "$INTERFACE"
+		else
+			echo "[!] Missing WireGuard kernel module or userspace implementation." >&2
+			exit $ret
+		fi
 	fi
 }
 
